
package ru.anovikov.test.testgcsadp;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-01T01:35:31.343+03:00
 * Generated source version: 3.3.4
 *
 */
public final class InterGateIBankWs_InterGateIbankWs_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.ibank.gate.inter.gcs", "InterGateIbankWsImplService");
    // private static final QName SERVICE_NAME = new QName("http://ws.ibank.gate.inter.gcs/wsdl", "InterGateIbankWsImplPort");

    private InterGateIBankWs_InterGateIbankWs_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InterGateIBankWsService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        InterGateIBankWsService ss = new InterGateIBankWsService(wsdlURL, SERVICE_NAME);
        InterGateIBankWs port = ss.getInterGateIbankWs();

        {
        System.out.println("Invoking pmntEx...");
        java.lang.String _pmntEx_msgType = "";
        java.lang.String _pmntEx_msgData = "";
        java.lang.String _pmntEx_sign = "";
        java.lang.String _pmntEx_extCode = "";
        java.lang.String _pmntEx_extId = "";
        java.lang.String _pmntEx_cardNo = "";
        java.lang.String _pmntEx_pmntExtId = "";
        java.lang.String _pmntEx_pmntMode = "";
        java.lang.String _pmntEx_pmntType = "";
        java.lang.String _pmntEx_pmntData = "";
        java.math.BigInteger _pmntEx_amount = new java.math.BigInteger("0");
        java.lang.String _pmntEx_currency = "";
        java.util.List<ru.anovikov.test.testgcsadp.WsKeyPairDto> _pmntEx_params = null;
        ru.anovikov.test.testgcsadp.WsPmntExResponseDto _pmntEx__return = port.pmntEx(_pmntEx_msgType, _pmntEx_msgData, _pmntEx_sign, _pmntEx_extCode, _pmntEx_extId, _pmntEx_cardNo, _pmntEx_pmntExtId, _pmntEx_pmntMode, _pmntEx_pmntType, _pmntEx_pmntData, _pmntEx_amount, _pmntEx_currency, _pmntEx_params);
        System.out.println("pmntEx.result=" + _pmntEx__return);


        }
        {
        System.out.println("Invoking transInfo...");
        java.lang.String _transInfo_msgType = "";
        java.lang.String _transInfo_msgData = "";
        java.lang.String _transInfo_sign = "";
        java.lang.String _transInfo_extCode = "";
        java.lang.String _transInfo_extId = "";
        java.lang.String _transInfo_cardNo = "";
        javax.xml.datatype.XMLGregorianCalendar _transInfo_fromDt = null;
        javax.xml.datatype.XMLGregorianCalendar _transInfo_toDt = null;
        java.lang.String _transInfo_searchType = "";
        java.math.BigInteger _transInfo_utrnNo = new java.math.BigInteger("0");
        java.math.BigInteger _transInfo_count = new java.math.BigInteger("0");
        ru.anovikov.test.testgcsadp.WsTransInfoResponseDto _transInfo__return = port.transInfo(_transInfo_msgType, _transInfo_msgData, _transInfo_sign, _transInfo_extCode, _transInfo_extId, _transInfo_cardNo, _transInfo_fromDt, _transInfo_toDt, _transInfo_searchType, _transInfo_utrnNo, _transInfo_count);
        System.out.println("transInfo.result=" + _transInfo__return);


        }
        {
        System.out.println("Invoking cardChgGeoRestriction...");
        java.lang.String _cardChgGeoRestriction_msgType = "";
        java.lang.String _cardChgGeoRestriction_msgData = "";
        java.lang.String _cardChgGeoRestriction_sign = "";
        java.lang.String _cardChgGeoRestriction_extCode = "";
        java.lang.String _cardChgGeoRestriction_extId = "";
        java.lang.String _cardChgGeoRestriction_cardNo = "";
        java.lang.String _cardChgGeoRestriction_internetOnly3DS = "";
        java.util.List<ru.anovikov.test.testgcsadp.WsCardRestrictionDto> _cardChgGeoRestriction_params = null;
        ru.anovikov.test.testgcsadp.WsCardChgGeoRestrictionResponseDto _cardChgGeoRestriction__return = port.cardChgGeoRestriction(_cardChgGeoRestriction_msgType, _cardChgGeoRestriction_msgData, _cardChgGeoRestriction_sign, _cardChgGeoRestriction_extCode, _cardChgGeoRestriction_extId, _cardChgGeoRestriction_cardNo, _cardChgGeoRestriction_internetOnly3DS, _cardChgGeoRestriction_params);
        System.out.println("cardChgGeoRestriction.result=" + _cardChgGeoRestriction__return);


        }
        {
        System.out.println("Invoking cardInfo...");
        java.lang.String _cardInfo_msgType = "";
        java.lang.String _cardInfo_msgData = "";
        java.lang.String _cardInfo_sign = "";
        java.lang.String _cardInfo_extCode = "";
        java.lang.String _cardInfo_extId = "";
        java.lang.String _cardInfo_cardNo = "";
        ru.anovikov.test.testgcsadp.WsCardInfoResponseDto _cardInfo__return = port.cardInfo(_cardInfo_msgType, _cardInfo_msgData, _cardInfo_sign, _cardInfo_extCode, _cardInfo_extId, _cardInfo_cardNo);
        System.out.println("cardInfo.result=" + _cardInfo__return);


        }
        {
        System.out.println("Invoking cardInfoExt...");
        java.lang.String _cardInfoExt_msgType = "";
        java.lang.String _cardInfoExt_msgData = "";
        java.lang.String _cardInfoExt_sign = "";
        java.lang.String _cardInfoExt_extCode = "";
        java.lang.String _cardInfoExt_extId = "";
        java.lang.String _cardInfoExt_cardNo = "";
        ru.anovikov.test.testgcsadp.WsCardInfoExtResponseDto _cardInfoExt__return = port.cardInfoExt(_cardInfoExt_msgType, _cardInfoExt_msgData, _cardInfoExt_sign, _cardInfoExt_extCode, _cardInfoExt_extId, _cardInfoExt_cardNo);
        System.out.println("cardInfoExt.result=" + _cardInfoExt__return);


        }
        {
        System.out.println("Invoking tlcInfo...");
        java.lang.String _tlcInfo_msgType = "";
        java.lang.String _tlcInfo_msgData = "";
        java.lang.String _tlcInfo_sign = "";
        java.lang.String _tlcInfo_extCode = "";
        java.lang.String _tlcInfo_extId = "";
        java.lang.String _tlcInfo_cardNo = "";
        java.lang.String _tlcInfo_address = "";
        ru.anovikov.test.testgcsadp.WsTlcInfoResponseDto _tlcInfo__return = port.tlcInfo(_tlcInfo_msgType, _tlcInfo_msgData, _tlcInfo_sign, _tlcInfo_extCode, _tlcInfo_extId, _tlcInfo_cardNo, _tlcInfo_address);
        System.out.println("tlcInfo.result=" + _tlcInfo__return);


        }
        {
        System.out.println("Invoking cardChgLmt...");
        java.lang.String _cardChgLmt_msgType = "";
        java.lang.String _cardChgLmt_msgData = "";
        java.lang.String _cardChgLmt_sign = "";
        java.lang.String _cardChgLmt_extCode = "";
        java.lang.String _cardChgLmt_extId = "";
        java.lang.String _cardChgLmt_cardNo = "";
        java.lang.String _cardChgLmt_source = "";
        java.lang.String _cardChgLmt_type = "";
        java.lang.String _cardChgLmt_cycleType = "";
        java.math.BigInteger _cardChgLmt_value = new java.math.BigInteger("0");
        java.lang.String _cardChgLmt_currency = "";
        ru.anovikov.test.testgcsadp.WsCardChgLmtResponseDto _cardChgLmt__return = port.cardChgLmt(_cardChgLmt_msgType, _cardChgLmt_msgData, _cardChgLmt_sign, _cardChgLmt_extCode, _cardChgLmt_extId, _cardChgLmt_cardNo, _cardChgLmt_source, _cardChgLmt_type, _cardChgLmt_cycleType, _cardChgLmt_value, _cardChgLmt_currency);
        System.out.println("cardChgLmt.result=" + _cardChgLmt__return);


        }
        {
        System.out.println("Invoking pmntCheck...");
        java.lang.String _pmntCheck_msgType = "";
        java.lang.String _pmntCheck_msgData = "";
        java.lang.String _pmntCheck_sign = "";
        java.lang.String _pmntCheck_extCode = "";
        java.lang.String _pmntCheck_extId = "";
        java.lang.String _pmntCheck_cardNo = "";
        java.lang.String _pmntCheck_pmntExtId = "";
        java.lang.String _pmntCheck_pmntType = "";
        java.lang.String _pmntCheck_pmntData = "";
        java.math.BigInteger _pmntCheck_amount = new java.math.BigInteger("0");
        java.lang.String _pmntCheck_currency = "";
        ru.anovikov.test.testgcsadp.WsPmntCheckResponseDto _pmntCheck__return = port.pmntCheck(_pmntCheck_msgType, _pmntCheck_msgData, _pmntCheck_sign, _pmntCheck_extCode, _pmntCheck_extId, _pmntCheck_cardNo, _pmntCheck_pmntExtId, _pmntCheck_pmntType, _pmntCheck_pmntData, _pmntCheck_amount, _pmntCheck_currency);
        System.out.println("pmntCheck.result=" + _pmntCheck__return);


        }
        {
        System.out.println("Invoking pmnt...");
        java.lang.String _pmnt_msgType = "";
        java.lang.String _pmnt_msgData = "";
        java.lang.String _pmnt_sign = "";
        java.lang.String _pmnt_extCode = "";
        java.lang.String _pmnt_extId = "";
        java.lang.String _pmnt_cardNo = "";
        java.lang.String _pmnt_pmntExtId = "";
        java.lang.String _pmnt_pmntType = "";
        java.lang.String _pmnt_pmntData = "";
        java.math.BigInteger _pmnt_amount = new java.math.BigInteger("0");
        java.lang.String _pmnt_currency = "";
        ru.anovikov.test.testgcsadp.WsPmntResponseDto _pmnt__return = port.pmnt(_pmnt_msgType, _pmnt_msgData, _pmnt_sign, _pmnt_extCode, _pmnt_extId, _pmnt_cardNo, _pmnt_pmntExtId, _pmnt_pmntType, _pmnt_pmntData, _pmnt_amount, _pmnt_currency);
        System.out.println("pmnt.result=" + _pmnt__return);


        }
        {
        System.out.println("Invoking holdInfo...");
        java.lang.String _holdInfo_msgType = "";
        java.lang.String _holdInfo_msgData = "";
        java.lang.String _holdInfo_sign = "";
        java.lang.String _holdInfo_extCode = "";
        java.lang.String _holdInfo_extId = "";
        java.lang.String _holdInfo_cardNo = "";
        javax.xml.datatype.XMLGregorianCalendar _holdInfo_fromDt = null;
        javax.xml.datatype.XMLGregorianCalendar _holdInfo_toDt = null;
        java.lang.String _holdInfo_searchType = "";
        java.math.BigInteger _holdInfo_utrnNo = new java.math.BigInteger("0");
        java.math.BigInteger _holdInfo_count = new java.math.BigInteger("0");
        ru.anovikov.test.testgcsadp.WsHoldInfoResponseDto _holdInfo__return = port.holdInfo(_holdInfo_msgType, _holdInfo_msgData, _holdInfo_sign, _holdInfo_extCode, _holdInfo_extId, _holdInfo_cardNo, _holdInfo_fromDt, _holdInfo_toDt, _holdInfo_searchType, _holdInfo_utrnNo, _holdInfo_count);
        System.out.println("holdInfo.result=" + _holdInfo__return);


        }
        {
        System.out.println("Invoking cardGeoRestrictionInfo...");
        java.lang.String _cardGeoRestrictionInfo_msgType = "";
        java.lang.String _cardGeoRestrictionInfo_msgData = "";
        java.lang.String _cardGeoRestrictionInfo_sign = "";
        java.lang.String _cardGeoRestrictionInfo_extCode = "";
        java.lang.String _cardGeoRestrictionInfo_extId = "";
        java.lang.String _cardGeoRestrictionInfo_cardNo = "";
        ru.anovikov.test.testgcsadp.WsCardGeoRestrictionInfoResponseDto _cardGeoRestrictionInfo__return = port.cardGeoRestrictionInfo(_cardGeoRestrictionInfo_msgType, _cardGeoRestrictionInfo_msgData, _cardGeoRestrictionInfo_sign, _cardGeoRestrictionInfo_extCode, _cardGeoRestrictionInfo_extId, _cardGeoRestrictionInfo_cardNo);
        System.out.println("cardGeoRestrictionInfo.result=" + _cardGeoRestrictionInfo__return);


        }
        {
        System.out.println("Invoking cardBal...");
        java.lang.String _cardBal_msgType = "";
        java.lang.String _cardBal_msgData = "";
        java.lang.String _cardBal_sign = "";
        java.lang.String _cardBal_extCode = "";
        java.lang.String _cardBal_extId = "";
        java.lang.String _cardBal_cardNo = "";
        ru.anovikov.test.testgcsadp.WsCardBalResponseDto _cardBal__return = port.cardBal(_cardBal_msgType, _cardBal_msgData, _cardBal_sign, _cardBal_extCode, _cardBal_extId, _cardBal_cardNo);
        System.out.println("cardBal.result=" + _cardBal__return);


        }
        {
        System.out.println("Invoking pmntRev...");
        java.lang.String _pmntRev_msgType = "";
        java.lang.String _pmntRev_msgData = "";
        java.lang.String _pmntRev_sign = "";
        java.lang.String _pmntRev_extCode = "";
        java.lang.String _pmntRev_extId = "";
        java.lang.String _pmntRev_cardNo = "";
        java.lang.String _pmntRev_pmntExtId = "";
        java.lang.String _pmntRev_pmntType = "";
        java.lang.String _pmntRev_pmntData = "";
        java.math.BigInteger _pmntRev_amount = new java.math.BigInteger("0");
        java.lang.String _pmntRev_currency = "";
        ru.anovikov.test.testgcsadp.WsPmntRevResponseDto _pmntRev__return = port.pmntRev(_pmntRev_msgType, _pmntRev_msgData, _pmntRev_sign, _pmntRev_extCode, _pmntRev_extId, _pmntRev_cardNo, _pmntRev_pmntExtId, _pmntRev_pmntType, _pmntRev_pmntData, _pmntRev_amount, _pmntRev_currency);
        System.out.println("pmntRev.result=" + _pmntRev__return);


        }
        {
        System.out.println("Invoking cardChgStatus...");
        java.lang.String _cardChgStatus_msgType = "";
        java.lang.String _cardChgStatus_msgData = "";
        java.lang.String _cardChgStatus_sign = "";
        java.lang.String _cardChgStatus_extCode = "";
        java.lang.String _cardChgStatus_extId = "";
        java.lang.String _cardChgStatus_cardNo = "";
        java.lang.String _cardChgStatus_status = "";
        ru.anovikov.test.testgcsadp.WsCardChgStatusResponseDto _cardChgStatus__return = port.cardChgStatus(_cardChgStatus_msgType, _cardChgStatus_msgData, _cardChgStatus_sign, _cardChgStatus_extCode, _cardChgStatus_extId, _cardChgStatus_cardNo, _cardChgStatus_status);
        System.out.println("cardChgStatus.result=" + _cardChgStatus__return);


        }

        System.exit(0);
    }

}
