package ru.anovikov.test.testgcsadp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-01T01:35:31.444+03:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "InterGateIbankWsImplService",
        wsdlLocation = "http://localhost:8080/WebServiceProject/services/inter-gate-ibank-ws?wsdl",
        targetNamespace = "http://ws.ibank.gate.inter.gcs")
public class InterGateIBankWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.ibank.gate.inter.gcs/wsdl", "InterGateIBankWsService");
    public final static QName InterGateIbankWs = new QName("http://ws.ibank.gate.inter.gcs", "inter-gate-ibank-ws");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/WebServiceProject/services/inter-gate-ibank-ws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InterGateIBankWsService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://localhost:8080/WebServiceProject/services/inter-gate-ibank-ws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InterGateIBankWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterGateIBankWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterGateIBankWsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public InterGateIBankWsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InterGateIBankWsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InterGateIBankWsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns InterGateIBankWs
     */
    @WebEndpoint(name = "inter-gate-ibank-ws")
    public InterGateIBankWs getInterGateIbankWs() {
        return super.getPort(InterGateIbankWs, InterGateIBankWs.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterGateIBankWs
     */
    @WebEndpoint(name = "inter-gate-ibank-ws")
    public InterGateIBankWs getInterGateIbankWs(WebServiceFeature... features) {
        return super.getPort(InterGateIbankWs, InterGateIBankWs.class, features);
    }

}
