//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.26 at 08:38:56 PM MSK 
//


package gcs.inter.gate.ibank.ws.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gcs.inter.gate.ibank.ws.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gcs.inter.gate.ibank.ws.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CardInfo }
     * 
     */
    public CardInfo createCardInfo() {
        return new CardInfo();
    }

    /**
     * Create an instance of {@link WsRequestDto }
     * 
     */
    public WsRequestDto createWsRequestDto() {
        return new WsRequestDto();
    }

    /**
     * Create an instance of {@link WsMessageDto }
     * 
     */
    public WsMessageDto createWsMessageDto() {
        return new WsMessageDto();
    }

    /**
     * Create an instance of {@link CardInfoResponse }
     * 
     */
    public CardInfoResponse createCardInfoResponse() {
        return new CardInfoResponse();
    }

    /**
     * Create an instance of {@link WsCardInfoResponseDto }
     * 
     */
    public WsCardInfoResponseDto createWsCardInfoResponseDto() {
        return new WsCardInfoResponseDto();
    }

    /**
     * Create an instance of {@link CardBal }
     * 
     */
    public CardBal createCardBal() {
        return new CardBal();
    }

    /**
     * Create an instance of {@link CardBalResponse }
     * 
     */
    public CardBalResponse createCardBalResponse() {
        return new CardBalResponse();
    }

    /**
     * Create an instance of {@link WsCardBalResponseDto }
     * 
     */
    public WsCardBalResponseDto createWsCardBalResponseDto() {
        return new WsCardBalResponseDto();
    }

    /**
     * Create an instance of {@link TlcInfo }
     * 
     */
    public TlcInfo createTlcInfo() {
        return new TlcInfo();
    }

    /**
     * Create an instance of {@link TlcInfoResponse }
     * 
     */
    public TlcInfoResponse createTlcInfoResponse() {
        return new TlcInfoResponse();
    }

    /**
     * Create an instance of {@link WsTlcInfoResponseDto }
     * 
     */
    public WsTlcInfoResponseDto createWsTlcInfoResponseDto() {
        return new WsTlcInfoResponseDto();
    }

    /**
     * Create an instance of {@link HoldInfo }
     * 
     */
    public HoldInfo createHoldInfo() {
        return new HoldInfo();
    }

    /**
     * Create an instance of {@link HoldInfoResponse }
     * 
     */
    public HoldInfoResponse createHoldInfoResponse() {
        return new HoldInfoResponse();
    }

    /**
     * Create an instance of {@link WsHoldInfoResponseDto }
     * 
     */
    public WsHoldInfoResponseDto createWsHoldInfoResponseDto() {
        return new WsHoldInfoResponseDto();
    }

    /**
     * Create an instance of {@link TransInfo }
     * 
     */
    public TransInfo createTransInfo() {
        return new TransInfo();
    }

    /**
     * Create an instance of {@link TransInfoResponse }
     * 
     */
    public TransInfoResponse createTransInfoResponse() {
        return new TransInfoResponse();
    }

    /**
     * Create an instance of {@link WsTransInfoResponseDto }
     * 
     */
    public WsTransInfoResponseDto createWsTransInfoResponseDto() {
        return new WsTransInfoResponseDto();
    }

    /**
     * Create an instance of {@link PmntCheck }
     * 
     */
    public PmntCheck createPmntCheck() {
        return new PmntCheck();
    }

    /**
     * Create an instance of {@link PmntCheckResponse }
     * 
     */
    public PmntCheckResponse createPmntCheckResponse() {
        return new PmntCheckResponse();
    }

    /**
     * Create an instance of {@link WsPmntCheckResponseDto }
     * 
     */
    public WsPmntCheckResponseDto createWsPmntCheckResponseDto() {
        return new WsPmntCheckResponseDto();
    }

    /**
     * Create an instance of {@link Pmnt }
     * 
     */
    public Pmnt createPmnt() {
        return new Pmnt();
    }

    /**
     * Create an instance of {@link PmntResponse }
     * 
     */
    public PmntResponse createPmntResponse() {
        return new PmntResponse();
    }

    /**
     * Create an instance of {@link WsPmntResponseDto }
     * 
     */
    public WsPmntResponseDto createWsPmntResponseDto() {
        return new WsPmntResponseDto();
    }

    /**
     * Create an instance of {@link PmntRev }
     * 
     */
    public PmntRev createPmntRev() {
        return new PmntRev();
    }

    /**
     * Create an instance of {@link PmntRevResponse }
     * 
     */
    public PmntRevResponse createPmntRevResponse() {
        return new PmntRevResponse();
    }

    /**
     * Create an instance of {@link WsPmntRevResponseDto }
     * 
     */
    public WsPmntRevResponseDto createWsPmntRevResponseDto() {
        return new WsPmntRevResponseDto();
    }

    /**
     * Create an instance of {@link PmntEx }
     * 
     */
    public PmntEx createPmntEx() {
        return new PmntEx();
    }

    /**
     * Create an instance of {@link WsKeyPairDto }
     * 
     */
    public WsKeyPairDto createWsKeyPairDto() {
        return new WsKeyPairDto();
    }

    /**
     * Create an instance of {@link PmntExResponse }
     * 
     */
    public PmntExResponse createPmntExResponse() {
        return new PmntExResponse();
    }

    /**
     * Create an instance of {@link WsPmntExResponseDto }
     * 
     */
    public WsPmntExResponseDto createWsPmntExResponseDto() {
        return new WsPmntExResponseDto();
    }

    /**
     * Create an instance of {@link CardChgStatus }
     * 
     */
    public CardChgStatus createCardChgStatus() {
        return new CardChgStatus();
    }

    /**
     * Create an instance of {@link CardChgStatusResponse }
     * 
     */
    public CardChgStatusResponse createCardChgStatusResponse() {
        return new CardChgStatusResponse();
    }

    /**
     * Create an instance of {@link WsCardChgStatusResponseDto }
     * 
     */
    public WsCardChgStatusResponseDto createWsCardChgStatusResponseDto() {
        return new WsCardChgStatusResponseDto();
    }

    /**
     * Create an instance of {@link CardChgLmt }
     * 
     */
    public CardChgLmt createCardChgLmt() {
        return new CardChgLmt();
    }

    /**
     * Create an instance of {@link CardChgLmtResponse }
     * 
     */
    public CardChgLmtResponse createCardChgLmtResponse() {
        return new CardChgLmtResponse();
    }

    /**
     * Create an instance of {@link WsCardChgLmtResponseDto }
     * 
     */
    public WsCardChgLmtResponseDto createWsCardChgLmtResponseDto() {
        return new WsCardChgLmtResponseDto();
    }

    /**
     * Create an instance of {@link CardInfoExt }
     * 
     */
    public CardInfoExt createCardInfoExt() {
        return new CardInfoExt();
    }

    /**
     * Create an instance of {@link CardInfoExtResponse }
     * 
     */
    public CardInfoExtResponse createCardInfoExtResponse() {
        return new CardInfoExtResponse();
    }

    /**
     * Create an instance of {@link WsCardInfoExtResponseDto }
     * 
     */
    public WsCardInfoExtResponseDto createWsCardInfoExtResponseDto() {
        return new WsCardInfoExtResponseDto();
    }

    /**
     * Create an instance of {@link CardGeoRestrictionInfo }
     * 
     */
    public CardGeoRestrictionInfo createCardGeoRestrictionInfo() {
        return new CardGeoRestrictionInfo();
    }

    /**
     * Create an instance of {@link CardGeoRestrictionInfoResponse }
     * 
     */
    public CardGeoRestrictionInfoResponse createCardGeoRestrictionInfoResponse() {
        return new CardGeoRestrictionInfoResponse();
    }

    /**
     * Create an instance of {@link WsCardGeoRestrictionInfoResponseDto }
     * 
     */
    public WsCardGeoRestrictionInfoResponseDto createWsCardGeoRestrictionInfoResponseDto() {
        return new WsCardGeoRestrictionInfoResponseDto();
    }

    /**
     * Create an instance of {@link CardChgGeoRestriction }
     * 
     */
    public CardChgGeoRestriction createCardChgGeoRestriction() {
        return new CardChgGeoRestriction();
    }

    /**
     * Create an instance of {@link WsCardRestrictionDto }
     * 
     */
    public WsCardRestrictionDto createWsCardRestrictionDto() {
        return new WsCardRestrictionDto();
    }

    /**
     * Create an instance of {@link CardChgGeoRestrictionResponse }
     * 
     */
    public CardChgGeoRestrictionResponse createCardChgGeoRestrictionResponse() {
        return new CardChgGeoRestrictionResponse();
    }

    /**
     * Create an instance of {@link WsCardChgGeoRestrictionResponseDto }
     * 
     */
    public WsCardChgGeoRestrictionResponseDto createWsCardChgGeoRestrictionResponseDto() {
        return new WsCardChgGeoRestrictionResponseDto();
    }

    /**
     * Create an instance of {@link WsObjectDto }
     * 
     */
    public WsObjectDto createWsObjectDto() {
        return new WsObjectDto();
    }

    /**
     * Create an instance of {@link WsResponseDto }
     * 
     */
    public WsResponseDto createWsResponseDto() {
        return new WsResponseDto();
    }

    /**
     * Create an instance of {@link WsLimitDto }
     * 
     */
    public WsLimitDto createWsLimitDto() {
        return new WsLimitDto();
    }

    /**
     * Create an instance of {@link WsCardInfoDto }
     * 
     */
    public WsCardInfoDto createWsCardInfoDto() {
        return new WsCardInfoDto();
    }

    /**
     * Create an instance of {@link WsCardBalDto }
     * 
     */
    public WsCardBalDto createWsCardBalDto() {
        return new WsCardBalDto();
    }

    /**
     * Create an instance of {@link WsTlcCardServiceDto }
     * 
     */
    public WsTlcCardServiceDto createWsTlcCardServiceDto() {
        return new WsTlcCardServiceDto();
    }

    /**
     * Create an instance of {@link WsTlcCardDto }
     * 
     */
    public WsTlcCardDto createWsTlcCardDto() {
        return new WsTlcCardDto();
    }

    /**
     * Create an instance of {@link WsTlcInfoDto }
     * 
     */
    public WsTlcInfoDto createWsTlcInfoDto() {
        return new WsTlcInfoDto();
    }

    /**
     * Create an instance of {@link WsHoldDto }
     * 
     */
    public WsHoldDto createWsHoldDto() {
        return new WsHoldDto();
    }

    /**
     * Create an instance of {@link WsHoldInfoDto }
     * 
     */
    public WsHoldInfoDto createWsHoldInfoDto() {
        return new WsHoldInfoDto();
    }

    /**
     * Create an instance of {@link WsTransDto }
     * 
     */
    public WsTransDto createWsTransDto() {
        return new WsTransDto();
    }

    /**
     * Create an instance of {@link WsTransInfoDto }
     * 
     */
    public WsTransInfoDto createWsTransInfoDto() {
        return new WsTransInfoDto();
    }

    /**
     * Create an instance of {@link WsPmntBaseDto }
     * 
     */
    public WsPmntBaseDto createWsPmntBaseDto() {
        return new WsPmntBaseDto();
    }

    /**
     * Create an instance of {@link WsPmntCheckDto }
     * 
     */
    public WsPmntCheckDto createWsPmntCheckDto() {
        return new WsPmntCheckDto();
    }

    /**
     * Create an instance of {@link WsPmntDto }
     * 
     */
    public WsPmntDto createWsPmntDto() {
        return new WsPmntDto();
    }

    /**
     * Create an instance of {@link WsPmntRevDto }
     * 
     */
    public WsPmntRevDto createWsPmntRevDto() {
        return new WsPmntRevDto();
    }

    /**
     * Create an instance of {@link WsPmntExDto }
     * 
     */
    public WsPmntExDto createWsPmntExDto() {
        return new WsPmntExDto();
    }

    /**
     * Create an instance of {@link WsCardChgStatusDto }
     * 
     */
    public WsCardChgStatusDto createWsCardChgStatusDto() {
        return new WsCardChgStatusDto();
    }

    /**
     * Create an instance of {@link WsCardChgLmtDto }
     * 
     */
    public WsCardChgLmtDto createWsCardChgLmtDto() {
        return new WsCardChgLmtDto();
    }

    /**
     * Create an instance of {@link WsCardInfoExtDto }
     * 
     */
    public WsCardInfoExtDto createWsCardInfoExtDto() {
        return new WsCardInfoExtDto();
    }

    /**
     * Create an instance of {@link WsCardGeoRestrictionInfoDto }
     * 
     */
    public WsCardGeoRestrictionInfoDto createWsCardGeoRestrictionInfoDto() {
        return new WsCardGeoRestrictionInfoDto();
    }

    /**
     * Create an instance of {@link WsCardChgGeoRestrictionDto }
     * 
     */
    public WsCardChgGeoRestrictionDto createWsCardChgGeoRestrictionDto() {
        return new WsCardChgGeoRestrictionDto();
    }

}
