//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.26 at 08:38:56 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.ibank.gate.inter.gcs/types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gcs.inter.gate.ibank.ws.wsdl;
